<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFBN6iAX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFBN6iAX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFBN6iAX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFBN6iAX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFBN6iAX\App_KernelDevDebugContainer([
    'container.build_hash' => 'FBN6iAX',
    'container.build_id' => '4acfdd1b',
    'container.build_time' => 1656571392,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFBN6iAX');
