version: "3.8"
services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=keke
      - WORDPRESS_DB_PASSWORD=kevin
      - WORDPRESS_DB_NAME=wordp
    networks:
      - galaxie 
    volumes:
      - wp:/var/www/html
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=kevinou
      - MYSQL_DATABASE=wordp
      - MYSQL_USER=keke
      - MYSQL_PASSWORD=kevin
    networks:
      - galaxie
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
  wp:
networks:
  galaxie: